### PR TITLE
Display the search bar on the model like on the simulation view.

### PR DESCRIPTION
**Pull request by YohannParis**
**What**
- After changing the search bar on the simulation view, the model view was not on par.

**How**
- Clean up the Model view code and implemented the same ideas.
- Random cleanup around.

**Testing**
- The search bar is now hidden behind a toggle button, and the open simulation button match the close button on the simulation view.

### CODE REVIEW

**Comment by mj3cheun** [comment]
I pushed a hacky fix for the searchbar which originally didnt really work (the searchbar wouldnt slide out). need more investigation to come up with an elegant fix.

**Comment by YohannParis** [comment]
> I pushed a hacky fix for the searchbar which originally didnt really work (the searchbar wouldnt slide out). need more investigation to come up with an elegant fix.

Could you tell me which browser you are using. I had no issue on Firefox and Safari. I'll look into it tomorrow.

**Comment by mj3cheun** [comment]
Using chrome 91

**Review by RosaRomeroGomez — APPROVED** [review]
Thanks!

**Comment by YohannParis** [comment]
Please do not delete this branch. I would like to test and make sure why this hack was necessary.

**Comment by YohannParis** [comment]
I'm submiting the fix for the hack on another PR

**Pull request merged**
