### PR TITLE
Consolidated fixes 1

### PR DESCRIPTION
**Pull request by mj3cheun**
Solves the following issues:

- #289 
- #292
- #295
- #303
- #304
- #314

### CODE REVIEW

**Review by YohannParis — APPROVED** [review]
Looks fine and dandy

**Comment by RosaRomeroGomez** [comment]
Some comments:

- I think the goal for the save button was to make it look pressed or in other words, I think this button should actually act as a checkbox or toggle. So if it is checked (and it looks pressed), your runs are saved and displayed but if it is not, they are not saved and displayed. Let me know if this makes sense. 
- For line charts, I think we need to display fewer labels. d3 should allow you to define the interval for them.

**Comment by YohannParis** [comment]
>     * I think the goal for the save button was to make it look pressed or in other words, I think this button should actually act as a checkbox or toggle. So if it is checked (and it looks pressed), your runs are saved and displayed but if it is not, they are not saved and displayed. Let me know if this makes sense.

This is a completely new behaviour. I don't think it will mix well with the _Auto-run_ option, suddenly at every change of a parameters we save an extra run? This can create dozens of runs really fast.

**Comment by mj3cheun** [comment]
Let me know which save button behaviour you would prefer, I think either could work, although for the toggle behaviour I would be tempted to incorporate an actual checkbox into the button.

As for displaying fewer labels, I think that could be done in a separate PR as part of a larger task to make the line charts truly responsive.

**Review by RosaRomeroGomez — APPROVED** [review]

**Pull request merged**
