### PR TITLE
CSS custom properties

### LINKED ISSUE #99: Start using native CSS custom properties for style customization
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

### PR DESCRIPTION
**Pull request by YohannParis**
**What**
- fix #99 

**How**
- Created a new series of styles files using CSS
- Updated `rollup.config.js` to copy the CSS files as they are not processed, and remove the unused dev server.
- Removing all the references to SCSS variables and replacing them with CSS custom properties
- Took advantage of going through many files to organize CSS properties alphabetically and remove simple selector nesting. That might help SCSS pre-processing of so many components. (for me, it went from 40sec build to 15sec).
- Move _Nord_ colours as CSS files directly

### CODE REVIEW

**Comment by RosaRomeroGomez** [comment]
Some awkward behaviors I've seen from my tests:

- Dropdown menu in the Models view
image

- Border of the search bar
image
image

- In the Knowledge view, the drilldown panel seems to increase its size when you switch between the `Preview` and `Models` panes.

**Review by mj3cheun — APPROVED** [review]

**Comment by mj3cheun** [comment]
nothing more to add from my end, nice job

**Comment by YohannParis** [comment]
> Some awkward behaviors I've seen from my tests:
>     * Dropdown menu in the Models view
>     * Border of the search bar
>     * In the Knowledge view, the drilldown panel seems to increase its size when you switch between the `Preview` and `Models` panes.

@RosaRomeroGomez those are all fixed!

**Comment by RosaRomeroGomez** [comment]
Everything looks good now. I just noticed that we still have a blue outline for the search bar when we select it. We probably want to switch that to the yellow selection color:
image

**Comment by YohannParis** [comment]
> Everything looks good now. I just noticed that we still have a blue outline for the search bar when we select it. We probably want to switch that to the yellow selection color:
> image

This has been fixed, thanks for noticing.
Screen Shot 2021-07-12 at 09 46 21

**Review by RosaRomeroGomez — APPROVED** [review]

**Pull request merged**
